title: "me@hsinghhira.me ~ $"

owner: "Hi there! ğŸ‘‹"
info: >
  Welcome to my super cool corner of the internet! ğŸŒâœ¨ <br><br> I'm <b>Harman Singh Hira</b> but most people call me by my last name, Hira ğŸ’
desc: >
  So, I was born in Chandigarh, India ğŸ‡®ğŸ‡³ but in my early 20s, I made the big move to the beautiful island of New Zealand ğŸ‡³ğŸ‡¿.
  I finished all my studies back home, then added a diploma in Business Management & Leadership here just to keep things spicy ğŸ“âœ¨
  <br><br>

  Now rewind to when I was 15... while most of my friends were busy gaming ğŸ®, I was that one kid messing around with code ğŸ’».
  I started building websites, making templates, and yep, even sold a few for some decent cash ğŸ’¸.
  Also had a tech blog that actually made money through Google AdSense at just 16! Crazy right? ğŸ¤¯
  Oh, and fun fact: I never studied IT in school. Everything I know? Self-taught. YouTube + curiosity = the real MVPs ğŸ¤ğŸ“º
  <br><br>

  After moving to NZ, life got a bit busy. I had a full-time job (not in tech, more like pizza deliveries ğŸ•ğŸš—) and study life.
  So coding kind of took a pause. But I realized I missed it. Like, a lot.
  It's my kind of therapy: just me, the screen, and vibes ğŸ’¡âœ¨
  Started learning again, built some random tools (including some I totally regret, don't ask ğŸ˜…), and got back into the groove.
  <br><br>

  These days, I'm still deep-diving into all things tech, even though I work in a completely different industry.
  Why not full-time dev work? Tbh, the moment coding feels like work instead of fun, I lose all motivation ğŸ’€.
  I like building stuff on my own terms â€” when it's fun, not forced.
  <br><br>

  Right now, I'm happily married (wife's literally sitting next to me as I type this ğŸ˜„ğŸ’), love binge-watching movies ğŸ¬, exploring new places âœˆï¸, learning random things ğŸ§ , and yeah... FOOD.
  Huge foodie here ğŸœ and not to brag, but I'm kinda decent in the kitchen too ğŸ‘¨â€ğŸ³ğŸ”¥
  <br><br>

  Anyway, that's a lil' peek into my story.
  Thanks for stopping by!
  <br><br>

  Cheers ğŸ¥‚

menu:
  /blog: /blog
  /works: /works
  /contact: /contact

max_post: 4

tcolor: 0FA0CE

usercss:

footer: true
placename: Aotearoa
placelink: https://en.wikipedia.org/wiki/Aotearoa

nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒœ

favicon: /images/favicon.png
thumbnail:

article:
  thumbnail: false

disqus_enabled: false
disqus_shortname:
